### ISSUE TITLE
Test bubble_sort

### ISSUE THREAD

**Issue by Herriot65** [weissfennek/lglsi2-24#11]

**Comment by nassim-ali** [comment]
def bubble_sort(arr):
    n = len(arr)

    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    
    return arr

arr = [64, 34, 25, 12, 22, 11, 90]
sorted_arr = bubble_sort(arr)
print("Sorted array:", sorted_arr)

**Comment by weissfennek** [comment]
@nassim-ali this issue has already been taken by Yassineka99 (see assignees). So please select an other issue. Also you need to write the tests using pytest. The tests should then be added to the code in the repository (using commit, push and merge as described in the assignment).
