### ISSUE TITLE
verif palindrome

### ISSUE THREAD

**Issue by dhouhahmd** [weissfennek/lglsi2-24#48]
def verifier_palindrome(mot):
    """
    Cette fonction vérifie si un mot est un palindrome.
    """
    inverse = mot[::-1]
    if inverse == mot:
        print("Le mot est un palindrome.")
    else:
        print("Le mot n'est pas un palindrome.")

mot = input("Entrez un mot : ")
verifier_palindrome(mot)

**Comment by weissfennek** [comment]
@dhouhahmd it seems that the palindrome code has been added by @Douaac and not by you.
Please add your own code to the repository then create an issue where you put a link to the code to be tested.
I will close the issue as invalid.
