### ISSUE TITLE
calcule

### ISSUE THREAD

**Issue by roua04** [weissfennek/lglsi2-24#49]
def add(a, b):
    revenir a + b

def subtract(a, b):
    revenir a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error: Division by zero!"
    return a / b

print("Select operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")

choice = input("Enter choice (1/2/3/4): ")

if choix not in ['1', '2', '3', '4']:
    print("Invalid choice")
else:
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    if choice == '1':
        print("Result:", addition(num1, num2))
    elif choice == '2':
        print("Result:", soustraction(num1, num2))
    elif choice == '3':
        print("Result:", multiply(num1, num2))
    elif choice == '4':
        print("Result:", divide(num1, num2))

**Comment by weissfennek** [comment]
@roua04 You need to add the code to the repository (follow the steps in the assignment) then create an issue where you put a link to the code to be tested.
I will close this issue as invalid
