### ISSUE TITLE
Test Cars_shop

### ISSUE THREAD

**Issue by Yassineka99** [weissfennek/lglsi2-24#50]
https://github.com/weissfennek/lglsi2-24/blob/master/generated-code/Cars_shop.py

**Comment by weissfennek** [comment]
@Yassineka99 Please put a link to the file in the lglsi2-24 repository

**Comment by Yassineka99** [comment]
@weissfennek Done

**Comment by youssef-boukassoula** [comment]
@Yassineka99 votre code contient un  erreurs tu as un variable 'wallet' n'est pas declarer.
