### ISSUE TITLE
 collaborator

### ISSUE THREAD

**Issue by wissalyahia** [weissfennek/lglsi2-24#7]
Dear team,
I hope this message finds you well. I am actively interested in contributing to the project and believe that I can bring valuable insights and contributions to the project. To facilitate a smoother collaboration, I kindly request to be added as a collaborator to the project.
I am committed to the success of this project and am eager to contribute in any way possible. Please consider adding me as a collaborator, and I look forward to working together to enhance the project.
Thank you for your time and consideration.

Best regards,Wissal yahia

**Comment by weissfennek** [comment]
@wissalyahia I would prefer manually written text to text that is generated. one short sentence would suffice in this case.
An invitation has been sent to your account.
