### ISSUE TITLE
Test somme_carres_pairs

### ISSUE THREAD

**Issue by nassim-ali** [weissfennek/lglsi2-24#8]
https://github.com/weissfennek/lglsi2-24/blob/67c5fd7ada4bb1c9fc6541440514c2385b13f97c/generated-code/somme_carres_pairs.py

**Comment by Herriot65** [comment]
def carre(nombre):
    return nombre ** 2

def somme_carres_pairs(n):
    somme = 0
    for i in range(n):
        if i % 2 == 0:
            somme += carre(i)
        else:
            somme += i
    return somme

n = 10
resultat = somme_carres_pairs(n)
print("La somme des carrés des nombres pairs jusqu'à", n, "est :", resultat)

**Comment by weissfennek** [comment]
@nassim-ali , there is no need to post the code here. You can just give a link to the file that contains the code to be tested. Also please add the label test.

**Comment by weissfennek** [comment]
@Herriot65 If you would like to test this code, then please assign the issue to yourself.
You need to create a file that contains your pytests and commit them to the repository

**Comment by nassim-ali** [comment]
@weissfennek  done
